[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "test"
solc = "0.8.28"
ignored = ["**/_*.sol", "**/*_ignore_*.sol"]

remappings = [
    "@openzeppelin=./node_modules/@openzeppelin",
    "forge-std/=lib/forge-std/src/"
]

[fuzz]
runs = 500

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
testnet = "${TESTNET_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

[etherscan]
testnet = { key = "${ETHERSCAN_API_KEY}", url = "${TESTNET_VERIFIER_URL}", chain = 531050104 }
mainnet = { key = "${ETHERSCAN_API_KEY}", url = "${MAINNET_VERIFIER_URL}", chain = 50104 }
etherscanTestnet = { key = "${ETHERSCAN_API_KEY}", url = "${TESTNET_ETHERSCAN_VERIFIER_URL}", chain = 531050104 }
etherscanMainnet = { key = "${ETHERSCAN_API_KEY}", url = "${MAINNET_ETHERSCAN_VERIFIER_URL}", chain = 50104 }